baseurl = "https://www.requaos.com"
title = "Requaos"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

enableEmoji = true

#Uncomment to enable Discus comments
#disqusShortname = "ramonschiner"

[params]
  author = "Raymond Skinner"
  info = ["Backend Developer", "API Services", "ETL and ML Specialties"]
  description = "Raymond Skiner's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"
  #gravatar = "john.doe@example.com"

  favicon_32 = "images/favicon-32x32.png"
  favicon_16 = "images/favicon-16x16.png"

  footercontent = "科技无国界"
  hideFooter = false
  hideCredits = false
  hideCopyright = false
  since = 2009

  enableTwemoji = false

  colorScheme = "auto"
  hidecolorschemetoggle = false

  customCSS = []
  customSCSS = []
  customJS = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/requaos/"
[[params.social]]
  name = "Gitlab"
  icon = "fa fa-gitlab fa-2x"
  weight = 2
  url = "https://gitlab.com/reqpro/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/requaos/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
